### ISSUE TITLE
[Feature] Add mark groups

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#10]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

Actually, there is only one virtual "group" of marks, a single stack.

When a user switches among buffers, he has to do multiple tasks: adding code, analyzing data, and so on, even for different projects.

If a single stack is implemented, this could lead to some confusion: navigating among multiple marks before finding the wished locations, might be confusing and distracting.

### Describe the solution you'd like

My proposal is to implement more stacks: all of the common commands would remain the same, but it would be possible to specify the stack group where the command should apply.

Example:

```
<A-1>     add mark to stack group 1
<A-2>     add mark to stack group 2

<C-1>     navigate to next mark of group 1
<S-1>     navigate to previous mark of group 1

<C-2>     navigate to next mark of group 2
...
```

Or:

```
<A-1>     Select stack group 1
<A-2>     Select stack group 2
...

<A-Right> navigate to next mark of current stack group
<A-Left>  navigate to previous mark of current stack group
```

Or:

```
<A-m>     Open a menu to select the stack group

<A-Right> navigate to next mark of current stack group
<A-Left>  navigate to previous mark of current stack group
```

Stack groups could be associated to:

* Document
* Places where to edit code
* Locations of interest
* Code lines of a specific project

and so on. It would improve mark navigation a lot, in my opinion.

### Describe alternatives you've considered

N/A

**Comment by LeonHeidelbach** [comment]
This is also a very good idea. I think I will implement it the way you described in the second variation. This means users will be able to select the current trail mark stack in a list of stacks (i.e. groups) and all subsequent marks will be added to the selected group as well as all actions/moves will only apply to the selected group until another group switch occurs. A selection menu could also be a good idea and implemented later on.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 These are all very good suggestions. However, this will probably take a little longer to implement, so I will most likely not be able to work on this today. I'll let you know in this issue once it's done.

**Comment by pidgeon777** [comment]
Don't worry @LeonHeidelbach, take your time 👍.

I'm confident those suggestions would greatly improve your plugin overall, adding features missing from the already available plugins.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 This feature has been implemented. You can now add new named stacks through the new user commands. You will find a detailed overview in the updated README as well as the new default keybindings. Let me know what you think. Closing this issue.
