### ISSUE TITLE
[Bug] `trailblazer.nvim` plugin crashes after deleting a buffer containing marks

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#12]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-454+g6d7b94ea0

### Operating system/version

Windows 10 x64 Pro

### Describe the bug

`trailblazer.nvim` plugin crashes after deleting a buffer containing marks and subsequently executing one of those commands:

- `TrailBlazerPeekMoveNextDown`
- `TrailBlazerPeekMoveNextUp`
- `TrailBlazerNewTrailMark`

![image](https://user-images.githubusercontent.com/13739892/215781488-b8662afc-6616-430c-974d-e2b0bcfb1d7a.png)

### Steps To Reproduce

1. Open buffer `A`.
2. Place a mark on buffer `A`.
3. Open buffer `B`.
4. Place a mark on buffer `B`.
5. Delete buffer `A`.
6. Execute any of the following `TrailBlazer` commands:

- `TrailBlazerPeekMoveNextDown`
- `TrailBlazerPeekMoveNextUp`
- `TrailBlazerNewTrailMark`

This leads to Neovim plugin error messages.

### Expected Behavior

In my opinion, when a buffer gets "killed", all marks associated with that buffer should be removed from the marks list, for each mark group.

Or, before switching to a mark, it should be at least checked if the next/previous mark to be switched, still exists:
- If yes, switch to it.
- If no, remove it and switch to the nearest next/previous mark.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 This should also be fixed now. Thank you for creating issues for these :+1: .

**Comment by pidgeon777** [comment]
Confirm it is fixed. Great work! 👍
