### ISSUE TITLE
[Bug] `trailblazer.nvim` crashes when switching to another trail mark stack after Neovim startup

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#13]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-454+g6d7b94ea0

### Operating system/version

Windows 10 x64 Pro

### Describe the bug

Let's consider a config like this:

```lua
default_trail_mark_stacks = {
    "Notes",
    "Debug",
    "Todo",
}
```

When starting Neovim and executing one of the following commands:

- `TrailBlazerSwitchNextTrailMarkStack`
- `TrailBlazerSwitchPreviousTrailMarkStack`

Then the following error is thrown:

![image](https://user-images.githubusercontent.com/13739892/215785720-f93ff0e5-d0d4-46a4-a0b0-bb489d0bf53e.png)

### Steps To Reproduce

1. Configure `trailblazer.nvim` default groups as shown above.
2. Start Neovim.
3. Execute one of the following commands:
   - `TrailBlazerSwitchNextTrailMarkStack`
   - `TrailBlazerSwitchPreviousTrailMarkStack`
4. An error is thrown.

### Expected Behavior

The proper behaviour would be to switch to the next/previous trail mark stack with no error.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 This only happens if you delete the "default" entry from the table. I will look into this right now.

**Comment by LeonHeidelbach** [comment]
Should be fixed now.

**Comment by pidgeon777** [comment]
Confirm it is fixed. Great work! 👍
