### ISSUE TITLE
feature: non-inclusive mappings

### ISSUE THREAD

**Issue by luiz00martins** [LeonHeidelbach/trailblazer.nvim#15]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

I intend to set up only a couple of mappings, but exclude most of them.

### Describe the solution you'd like

Here's my suggestion: 

Currently the `mappings` option is inclusive. That is: _The default mapping is always created unless specifically changed_.

It would be nice to have the option to make the mappings non-inclusive. That is: _The mapping will **not** be created, unless it's overtly specified_.

So for example:
```lua
inclusive_mappings = true, -- the default
mappings = {
	nv = {
		motions = {
			new_trail_mark = ',ba',
			track_back = ',bb',
			peek_move_next_down = ',bh',
			peek_move_previous_up = ',bl',
		},
	},
},
```
would change the mappings mentioned, and create all the other ones as default.

On the other hand:
```lua
inclusive_mappings = false, -- changed
mappings = {
	nv = {
		motions = {
			new_trail_mark = ',ba',
			track_back = ',bb',
			peek_move_next_down = ',bh',
			peek_move_previous_up = ',bl',
		},
	},
},
```
this would _only_ create the 4 mappings specified, and no others.

And also:
```lua
inclusive_mappings = false,
mappings = nil,
```
this would exclude all mappings, which is neat side-effect feature of this option. It can act as a toggle on/off for the mappings.

### Describe alternatives you've considered

Disable all mappings and create the desired mappings myself in a different file.

**Comment by LeonHeidelbach** [comment]
@luiz00martins This has been implemented. Specific default keymaps as well as the entire mappings sub-table can now be disabled by setting their values to either an empty string or false.

**Comment by luiz00martins** [comment]
Are you sure? My other bug report (#16) is completely separate from this feature request. The commit solves that issue, but not this one.

The main driver for this feature request is that, say I want only 2 mappings. Currently I have to manually disable all the other ones:
```lua
mappings = {
	nv = {
		motions = {
			new_trail_mark = ',ba',
			track_back = ',bb',
			peek_move_next_down = '',
			peek_move_previous_up = '',
		},
		actions = false,
	},
},
```

Instead of only mentioning the ones I actively want:
```lua
inclusive_mappings = false,
mappings = {
	nv = {
		motions = {
			new_trail_mark = ',ba',
			track_back = ',bb',
		},
	},
},
```
Despite being more verbose, this could cause some weird shenanigans if the plugin decides to add any new mapping (since it would not mentioned in the config, it would generate, and you'd have to come back to manually disable it).

It's fine if you want to reject the feature request. You may 'close as not planned'.

I think that commit doesn't address this issue though.

**Comment by LeonHeidelbach** [comment]
@luiz00martins I think adding another config option for this would make things a bit confusing. I instead implemented it a little differently. If you now rename the table key `mappings` to `foce_mappings` your mappings table will not be merged with the default bindings. This should do what you want.

**Comment by luiz00martins** [comment]
If I'm understanding correctly, the following config should disable all mappings:
```lua
require('trailblazer').setup {
	foce_mappings = {},
}
```
but it seems like that's not the case. Am I misinterpreting the option?

**Comment by LeonHeidelbach** [comment]
@luiz00martins My bad, I misspelled the option in my comment so you missed the "r". It's of course "force_mappings". Sorry about that. :wink:

**Comment by luiz00martins** [comment]
Makes more sense, I was still wondering what `foce` meant :laughing: 

Yes, it works! Thank you for the update!

**Comment by LeonHeidelbach** [comment]
Yeah, it definitely does :laughing:. I'm gonna quickly fix up my comment above so that no one else encounters the same problem.
