### ISSUE TITLE
bug: error when specifying an empty string `''` in a `mappings` option

### ISSUE THREAD

**Issue by luiz00martins** [LeonHeidelbach/trailblazer.nvim#16]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-849+g7880eeb2e

### Operating system/version

Pop!_OS 22.04 LTS

### Describe the bug

_Note: I don't know if this a bug or a feature request._

Setting a `mappings` options as an empty string (`''`) but instead yields an error.

### Steps To Reproduce

Use the following mapping config:
```lua
mappings = {
	nv = {
		motions = {
			new_trail_mark = '',
		},
	},
},
```

Which will yield an error similar to the following:
```
Failed to run `config` for trailblazer.nvim

vim/keymap.lua:0: Invalid (empty) LHS

# stacktrace:
  - vim/keymap.lua:0 _in_ **set**
  - /trailblazer.nvim/lua/trailblazer/keymaps.lua:49 _in_ **register_for_buf**
  - /trailblazer.nvim/lua/trailblazer/keymaps.lua:22 _in_ **register_api_maps**
  - /trailblazer.nvim/lua/trailblazer/init.lua:159 _in_ **setup**
  - .config/nvim/init/plugins_portable.lua:1139 _in_ **config**
  - lua:40
```

### Expected Behavior

Disable (do not create) the mapping if specified with an empty string.

**Comment by LeonHeidelbach** [comment]
@luiz00martins This has been implemented. Specific default keymaps as well as the entire mappings sub-table can now be disabled by setting their values to either an empty string or false.
