### ISSUE TITLE
bug: disabled signs still expands signs column if `number_line_color_enabled` is `true`

### ISSUE THREAD

**Issue by luiz00martins** [LeonHeidelbach/trailblazer.nvim#17]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-849+g7880eeb2e

### Operating system/version

Pop!_OS 22.04 LTS

### Describe the bug

Using the following config, which disables all signs, only allowing `number_line_color_enabled`:
```lua
trail_options = {
        multiple_mark_symbol_counters_enabled = false,
        number_line_color_enabled = true,
        trail_mark_in_text_highlights_enabled = false,
        trail_mark_symbol_line_indicators_enabled = false,
        symbol_line_enabled = false,
}
```

Creating a new mark still expands the signs column. Furthermore, popping the mark does not collapse the signs column:

https://user-images.githubusercontent.com/43142209/216399206-206793ec-c409-4f68-bd87-8e750ea1f95f.mp4

### Steps To Reproduce

1. Use the following `trail_options`:
```lua
trail_options = {
        multiple_mark_symbol_counters_enabled = false,
        number_line_color_enabled = true,
        trail_mark_in_text_highlights_enabled = false,
        trail_mark_symbol_line_indicators_enabled = false,
        symbol_line_enabled = false,
}
```
2. Create a new mark.

_Note: The issue does not happen if you also set `number_line_color_enabled = false`_

### Expected Behavior

Signs column only expand if a sign setting is enabled.

**Comment by LeonHeidelbach** [comment]
@luiz00martins This seems to be an issue with neovims implementation of the auto width feature for the sign column. The option `number_line_color_enabled = false` only disables setting the inverted highlight group for the number column. Can you try setting the sign column width variable to`vim.opt.signcolumn = "yes"` or  `vim.opt.signcolumn = "yes:2"`? This should fix it.

**Comment by luiz00martins** [comment]
`vim.opt.signcolumn = "yes"` would not behave as I'm expecting, as I don't want to have the sign column always displaying.

I  _want_ it to be `auto`, I just don't want it to be expanded by `number_line_color_enabled = true`.

If this is a neovim issue, I think it should be upstreamed.

**Comment by LeonHeidelbach** [comment]
@luiz00martins Yeah, unfortunately I don't think this currently works in Neovim 0.8 or 0.9. As you can see right [here](https://github.com/LeonHeidelbach/trailblazer.nvim/blob/59b3cc2ee1d1d11f9e1cbc18baa5da520ab53d08/lua/trailblazer/trails/common.lua#L528) the only thing changing the variable `number_line_color_enabled = true` does is add the inverted highlight group to the number column, which should not have any impact on the width of the sign column, unless I'm missing something.

**Comment by luiz00martins** [comment]
If that's the case, I'll test a bit tomorrow (I can't today) to see if I can replicate it, and I'll upstream it to `neovim` to see what they think about it.

**Comment by LeonHeidelbach** [comment]
I don't currently see what else it could be. Let me know if you find out more.

**Comment by LeonHeidelbach** [comment]
Closing this, as it is not a TrailBlazer issue, I hope this does get fixed soon though.
