### ISSUE TITLE
[Bug] 'TrailBlazerDeleteTrailMarkStack' command clears stack content but not the stack itself

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#19]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-454+g6d7b94ea0

### Operating system/version

Windows 10 21H2

### Describe the bug

'TrailBlazerDeleteTrailMarkStack' command clears stack content but not the stack itself.

### Steps To Reproduce

1. Start Neovim with no session.
2. Open a buffer.
3. Create a trailmark stack with `:TrailBlazerSwitchTrailMarkStack <name_of_stack>`.
4. Delete the trailmark stack with `:TrailBlazerDeleteTrailMarkStack`.

### Expected Behavior

The trailmark stack is completely deleted, not just the content, and after deletion, if the deleted stack was the current stack, the previous/next stack is automatically switched.

Or, the `TrailBlazerDeleteTrailMarkStack` command could be removed and instead added:

- `TrailBlazerClearTrailMarkStack`: clear the content of the current / specified trailmark stack.
- `TrailBlazerDeleteTrailMarkStack`: delete the current / specified trailmark stack, removing it from the list of stacks.

It would be nice to add some options/commands to simply clear the content of a stack, or to delete the stack itself removing it from the list of stacks.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 Should be fixed now. `:TrailBlazerDeleteAllTrailMarks` does already delete all trail marks from the current stack. `:TrailBlazerDeleteTrailMarkStack` should either delete the current or the specified trail mark stack. I must have broken this during an update. Good catch :+1:
