### ISSUE TITLE
[Bug] Multiple duplicated entries in trailmarks quickfix window

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#20]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-454+g6d7b94ea0

### Operating system/version

Windows 10 21H2

### Describe the bug

Multiple duplicated entries in the trailmarks quickfix window.

### Steps To Reproduce

Pre-requisites: a trailmark session file containing at least 2 trailmark stacks, containing each at least one mark.

Steps to reproduce:

1. Start Neovim with no session.
2. Open the trailmark list (`TrailBlazerToggleTrailMarkList`).
3. Open the trailarms session.
4. Switch to the next/previous trailmark stack.

The trailmark list (`quickfix`) for the selected stack will contain multiple duplicated entries, as follow:

```
trailmark 1
trailmark 2
trailmark 3
trailmark 1
trailmark 2
trailmark 3
...
```

a repeated list of the trailmarks for the selected stack. In my setup, the original list is repeated `24` times in the quickfix window.

Example:

![image](https://user-images.githubusercontent.com/13739892/218342854-29d81e9a-bda0-4259-8aaa-923154cd03d7.png)

Under this condition, the `quickfix` window with the trailmark list is cleaned of duplicates when switching to the next or previous trailmark of the current stack.

It is important to note that the duplicates seem to randomly appear in the `quickfix` window and that the number of duplicates for my current session file is equal to `k * 24`, where `k` is the number of trailmarks of the selected stack. So, if a stack has `3` trailmarks, then I see multiple duplicated groups of marks, for a total of `72`.

### Expected Behavior

No duplicated trailmarks should be reported in the trailmarks list `quickfix`.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 I cannot seem to reproduce this behavior. Can you maybe post a quick video of what you are doing? Could you also try to reproduce this on the current stable version of Neovim?

**Comment by LeonHeidelbach** [comment]
@pidgeon777 Should be fixed now. The issue was that when loading a session file one or multiple times, duplicate trail marks relative to their position and buffer were not removed.

**Comment by pidgeon777** [comment]
After some tests, the issue still seems to persist. Maybe still related to Windows paths?

**Comment by LeonHeidelbach** [comment]
@pidgeon777 I could not actually reproduce the issue you described on my machine until I loaded a session save file multiple times and the marks appeared exactly as many times as I loaded the session. When following the steps you listed it just worked as expected on my Linux machine. It might again be a Windows issue, I can test it on my Windows machine later. Could you post a quick screen capture of what exactly happens and what you are doing alongside the session save file that you are loading in?

**Comment by LeonHeidelbach** [comment]
@pidgeon777 I tried to reproduce your issue on Windows and everything just works as expected. Could this possibly be an issue with the current dev build of Neovim? Can you try to reproduce this with the current stable build of Neovim?
