### ISSUE TITLE
[Feature] Option to automatically open the trailmark list when navigating trailmarsk

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#21]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

Improve usability.

### Describe the solution you'd like

It would be nice to have an option (i.e. `trail_mark_list_auto_open`) to automatically open the trailmark list (`quickfix`) when navigating trailmarks.

### Describe alternatives you've considered

N/A.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 I don't think that this would be a useful global setting but I implemented two new user commands `:TrailBlazerOpenTrailMarkList` and `:TrailBlazerCloseTrailMarkList`. Using these commands you can simply create a custom key binding to achieve the desired behavior. Simply set the key maps in your configuration table to an empty string and register them manually like this:

```lua
function prev_trail_mark_plus_list_open()
    require("trailblazer").close_trail_mark_list()
    require("trailblazer").peek_move_previous_up()
end

function next_trail_mark_plus_list_open()
    require("trailblazer").close_trail_mark_list()
    require("trailblazer").peek_move_next_down()
end

vim.keymap.set("n", "<A-J>", next_trail_mark_plus_list_open, { noremap = true, silent = true })
vim.keymap.set("v", "<A-K>", prev_trail_mark_plus_list_open, { noremap = true, silent = true })
```

**Comment by FelixKratz** [comment]
I have implemented a mapping for something like this when creating a new mark (even with custom quickfix list height):
```lua
vim.api.nvim_set_keymap("n", "<C-m>", ':lua require("trailblazer").new_trail_mark() require("trailblazer").open_trail_mark_list() vim.cmd("cclose") vim.cmd("copen 5") require("trailblazer").peek_move_previous_up()<CR>', opts)
```
The way this works is that we:
* first create a new mark  
* then open the list via the trailblazer api
*  then close the list via vim api
*  open the list via vim api with the custom height
* then peek move to the previous mark (which is the one that was just created).

-> the list is open (with custom height) and the cursor is still where it was before opening the list.

**Comment by LeonHeidelbach** [comment]
@FelixKratz The default number of rows for all trail mark list types can now be set using the configuration option `trail_options.trail_mark_list_rows` 43ff5d6993ae2ebd97ea24bcebab1780892eba75. Additionally, the number of rows can now also be specified as a third parameter to the `:TrailBlazerOpenTrailMarkList` user command (e.g. `:TrailBlazerOpenTrailMarkList quickfix 0 5`.) or the api function (e.g. `require('trailblazer').open_trail_mark_list(nil, nil, 5)`). This should make things a little cleaner :wink:.

**Comment by FelixKratz** [comment]
I have found a better way to open the trailmark list without loosing the current cursor position, it should be more robust and work on all other mappings as well:
```lua
:lua require("trailblazer").open_trail_mark_list()<CR>:wincmd p<CR>
```

**Comment by pidgeon777** [comment]
I think the `:lua require("trailblazer").open_trail_mark_list()` could be improved.

Actually, if the mark list is already open and that command is executed, the list receives some refresh.

I would expect no operations if the list is already open.

Maybe a `:lua require("trailblazer").refresh_trail_mark_list()` command could be added, instead?

Anyway, executing the `open_trail_mark_list()` command multiple times would slow things down in the actual implementation.

What do you think @LeonHeidelbach?

**Comment by pidgeon777** [comment]
For completeness, the definitive mark list commands could be:

`lua require("trailblazer").open_trail_mark_list()`

=> Open the list if closed, do nothing if already open.

`lua require("trailblazer").close_trail_mark_list()`

=> Close the list.

`lua require("trailblazer").focus_trail_mark_list()`

=> Focus the list placing cursor in it, open the list if closed.

`lua require("trailblazer").toggle_trail_mark_list()`

=> Open the mark list if closed, close it if open.

`lua require("trailblazer").refresh_trail_mark_list()`

=> Refresh the list, open the list if closed.

**Comment by FelixKratz** [comment]
> `lua require("trailblazer").open_trail_mark_list()`
> 
> => Open the list if closed, do nothing if already open.

I disagree, it should still focus the list if the list is already open.

**Comment by pidgeon777** [comment]
@FelixKratz 

Even with my proposal implemented, you still could do something like this:

1. `:lua require("trailblazer").open_trail_mark_list()`
2. `:lua require("trailblazer").focus_trail_mark_list()`
3. `:wincmd p`

bound to a single key. Am I right @LeonHeidelbach? Maybe I missed something.

**Comment by FelixKratz** [comment]
Optimally `require("trailblazer").open_trail_mark_list()` wouldnt focus the list at all.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 The API function `:lua require("trailblazer").open_trail_mark_list()` as well as the respective user command `TrailBlazerOpenTrailMarkList` no longer update the quickfix list if it is not necessary a01a5bbf5ca9cf6b0773daec3e89046a36f77d7b.

Unfortunately there is no "official" way of stopping Neovim from moving the cursor into the quickfix buffer when calling `copen` (at least as far as I know). So the only way to achieve somewhat of the same behavior as of now is to use @FelixKratz's solution and register a key map like this `:lua require("trailblazer").open_trail_mark_list()<CR>:wincmd p<CR>`. If anyone knows a more elegant way of preventing the cursor from moving to the quickfix buffer let me know. I don't think that introducing more API functions to move the cursor into the quickfix buffer or refreshing the quickfix list manually is necessary. Focussing the quickfix list can simply be achieved by calling `copen` manually if needed and the list itself should automatically update itself if necessary so there is no need for manual access to a refresh function.
