### ISSUE TITLE
bug: typo in api

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#27]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

69

### Operating system/version

13

### Describe the bug

https://github.com/LeonHeidelbach/trailblazer.nvim/blob/c5cfc7effeb38b193688d264019a152b06f2463c/lua/trailblazer/init.lua#L339

### Steps To Reproduce

...

### Expected Behavior

...

**Comment by LeonHeidelbach** [comment]
Fixed 4ffbeac5599ebde1515721c5ba037e5677e68dea.
