### ISSUE TITLE
bug: prompt on trail mark stack deletion

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#28]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

macOS 13

### Describe the bug

Prompt appears when removing a trail mark stack which interrupts workflow:

![Screenshot 2023-02-27 at 12 27 56](https://user-images.githubusercontent.com/22680421/221552747-c16c2241-57a1-4ee9-994c-b61f24159817.png)

### Steps To Reproduce

- Create stack
- Select stack
- Remove stack

### Expected Behavior

No prompt to press enter.

**Comment by LeonHeidelbach** [comment]
Should be fixed now 4ffbeac5599ebde1515721c5ba037e5677e68dea.
