### ISSUE TITLE
bug: Deleting the only custom stack makes the default stack inaccessible

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#29]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

13

### Describe the bug

When deleting the only custom stack, e.g. defs, I am not returned to the default stack and it is not available in the stack cycling. Additionally, when creating a new mark it is created in the deleted defs list.

![Screenshot 2023-02-27 at 12 37 59](https://user-images.githubusercontent.com/22680421/221554575-a909a570-e8c5-4561-9103-27e087d5617c.png)

### Steps To Reproduce

* Add a custom stack and leave the default stack intact via:
```lua
require("trailblazer").switch_trail_mark_stack(name)
```

* Add some marks, do whatever in the new stack
* Remove the stack via:
```lua
require("trailblazer").delete_trail_mark_stack()
```

### Expected Behavior

The custom stack is removed and I am returned to the default stack.

**Comment by LeonHeidelbach** [comment]
Should be fixed now 4ffbeac5599ebde1515721c5ba037e5677e68dea.
