### ISSUE TITLE
feature: Sessions on a file level

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#34]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

Currently sessions seem to be connected to the folder. I want sessions to be only relevant for single files.

If I load a session it should only load the session for the currently open files. I.e. if I edit my .zshrc and have a session there and then edit another file in my home directory I dont want the .zshrc session to interfere.

### Describe the solution you'd like

Sessions should be on a buffer level.

### Describe alternatives you've considered

--

**Comment by FelixKratz** [comment]
This is also a problem if I, for example, edit a file by entering its absolute path (without calling chdir). The session will not be loaded when I edit the file from a different directory. This could be fixed by checking all session files if the current file is contained in any of the sessions, loading the first session where the current file is contained.

**Comment by FelixKratz** [comment]
I would like to use the configured
```lua
custom_session_storage_dir = "~/tb_sessions/",
```
without hardcoding it in my keybinding, would it perhaps be better to separate dir and filename arguments in both signatures, such that I dont have to specify the path but only the name of the file?

**Comment by FelixKratz** [comment]
This doesn't seem to work:
```lua
vim.api.nvim_set_keymap("n", "<Esc>l", ':lua local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0))) require("trailblazer").load_trailblazer_state_from_file(file, false) require("trailblazer").open_trail_mark_list()<CR>:wincmd p<CR>', opts)
vim.api.nvim_set_keymap("n", "<Esc>s", ':lua local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0))) require("trailblazer").save_trailblazer_state_to_file(file, nil, false) print("Saved Session")<CR>', opts)
```
It creates a file without the `.tbsv` file ending which I guess can not be loaded again? There is no error indicating this however.

This works:
```lua
vim.api.nvim_set_keymap("n", "<Esc>l", ':lua local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0))) .. ".tbsv" require("trailblazer").load_trailblazer_state_from_file(file, false) require("trailblazer").open_trail_mark_list()<CR>:wincmd p<CR>', opts)
vim.api.nvim_set_keymap("n", "<Esc>s", ':lua local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0))) .. ".tbsv" require("trailblazer").save_trailblazer_state_to_file(file, nil, false) print("Saved Session")<CR>', opts)
```

I would suggest that the `.tbsv` extension is added automatically if not specified and that the either the path is split into dir and file name or that relative paths, e.g. just the name, will automatically be adapted to include the configured/default storage dir.

**Comment by LeonHeidelbach** [comment]
> I would like to use the configured
> 
> ```lua
> custom_session_storage_dir = "~/tb_sessions/",
> ```
> 
> without hardcoding it in my keybinding, would it perhaps be better to separate dir and filename arguments in both signatures, such that I dont have to specify the path but only the name of the file?

Having two separate arguments would unnecessarily complicate things. You can simpy get the default value from TrailBlazers configuration table like this:

```lua
local default_storage_path = require("trailblazer").options.custom_session_storage_dir
```

> This doesn't seem to work:
> 
> ```lua
> vim.api.nvim_set_keymap("n", "<Esc>l", ':lua local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0))) require("trailblazer").load_trailblazer_state_from_file(file, false) require("trailblazer").open_trail_mark_list()<CR>:wincmd p<CR>', opts)
> vim.api.nvim_set_keymap("n", "<Esc>s", ':lua local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0))) require("trailblazer").save_trailblazer_state_to_file(file, nil, false) print("Saved Session")<CR>', opts)
> ```
> 
> It creates a file without the `.tbsv` file ending which I guess can not be loaded again? There is no error indicating this however.

Oh yes, I forgot about that. This is actually the inteded behavior and the reason for this is detailed in the [documentation](https://github.com/LeonHeidelbach/trailblazer.nvim#trail-mark-sessions). You will just have to add any file extension to your save path for it to work properly. There is no error message for this as this is not a bug but enables you to dynamically create session directories or save files depending on whether or not you add a file type extension.

**Comment by FelixKratz** [comment]
> If you pass either a directory or file name to :TrailBlazerSaveSession or :TrailBlazerLoadSession, the session will be saved into or loaded from the given directory or file. Note that you have to append any file extension (e.g. ".tbsv") to the file name argument when saving a session. Otherwise TrailBlazer will create a directory with the given name and save the session file named as the hashed path of the current working directory. Passing a directory name to :TrailBlazerLoadSession will cause TrailBlazer to search for a session file which matches the name of the hashed path of the current working directory.

Even after reading it again I have no clue what you want to tell me with this paragraph. I will just use the `default_storage_path` in my keybindings.

**Comment by LeonHeidelbach** [comment]
It's actually quite simple:

* `:TrailBlazerSaveSession sessions` will create the directory "sessions" in the current `cwd` and save all trail marks to a file named after the hashed value of the expanded `cwd` (i.e. `/home/<username>/projects/your_project` -> `5c33a1e23599584ac47ea3914ecec378ca4ab49f3fb9d9a6e54f0491a5dc8620.tbsv`) or create it if it doesn't yet exist.
* `:TrailBlazerSaveSession sessions/session_file.tbsv` will save all trail marks to a file named `session_file.tbsv` in the directory "sessions" or create it if it does not already exist within the current `cwd`.

**Comment by FelixKratz** [comment]
> It's actually quite simple:
> 
> * `:TrailBlazerSaveSession sessions` will create the directory "sessions" in the current `cwd` and save all trail marks to a file in this directory named after the hashed value of the expanded `cwd` (i.e. `/home/<username>/projects/your_project` -> `5c33a1e23599584ac47ea3914ecec378ca4ab49f3fb9d9a6e54f0491a5dc8620.tbsv`) or create it if it doesn't already exist.
> * `:TrailBlazerSaveSession sessions/session_file.tbsv` will save all trail marks to a file named `session_file.tbsv` in the directory "sessions" or create it if it does not already exist within the current `cwd`.

So why exactly doesn't this work then and why would that be expected behavior?
```lua
local file = vim.fn.stdpath("data") .. "/trailblazer/" .. vim.fn.sha256(vim.fn.expand(vim.api.nvim_buf_get_name(0)))
require("trailblazer").save_trailblazer_state_to_file(file, nil, false) 
```
followed by
```lua
require("trailblazer").load_trailblazer_state_from_file(file, false)
```
