### ISSUE TITLE
feature: Verbose flag for stack change

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#35]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

An option to disable the prints on stack change would be nice. Like it is for sort mode select:
```lua
verbose_trail_mark_select
```

### Describe the solution you'd like

```lua
verbose_trail_stack_select
```
in config would be nice.

### Describe alternatives you've considered

--

**Comment by LeonHeidelbach** [comment]
@FelixKratz An additional `verbose` parameter is now available for all relevant API functions 503c07812948a842e43cad432a7ce692db4c5832.
