### ISSUE TITLE
bug: Stack sorting is inverted after loading session

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#36]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

13

### Describe the bug

Stack ordering is exactly inverse after loading a session with multiple stacks:
<img width="1110" alt="Screenshot 2023-03-01 at 09 29 47" src="https://user-images.githubusercontent.com/22680421/222085445-45d987dd-39d5-4f7e-a862-c70655412aa3.png">

### Steps To Reproduce

* Create a session with multiple stacks
* Load the session
* All stacks except the initially selected one are ordered upside down

Adding a new mark to the stack re-sorts the list and the order is correct again.

### Expected Behavior

Correct sorting for all stacks.

**Comment by LeonHeidelbach** [comment]
@FelixKratz Should be fixed now 321b2a52addaa4062b9d6ac3f8eb05588d442416.
