### ISSUE TITLE
[Bug] Multiple execution of `TrailBlazerToggleTrailMarkList` leads to a crash

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#37]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

Windows 10 x64 Pro

### Describe the bug

Executing the `TrailBlazerToggleTrailMarkList` command three times leads to a crash:

```lua
E5108: Error executing lua Vim(lua):E5108: Error executing lua Vim:E952: Autocommand caused recursive behavior
stack traceback:
	[C]: in function 'setloclist'
	...ortable\Neovim\share\nvim\runtime/lua\vim\diagnostic.lua:494: in function 'set_list'
	...ortable\Neovim\share\nvim\runtime/lua\vim\diagnostic.lua:1462: in function 'setloclist'
	...pack\packer\start\diaglist.nvim/lua\diaglist\loclist.lua:24: in function 'diagnostics_hook'
	...te\pack\packer\start\diaglist.nvim/lua\diaglist\init.lua:63: in function 'diagnostics_hook'
	[string ":lua"]:1: in main chunk
	[C]: in function 'setqflist'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:201: in function 'populate_quickfix_list_with_trail_marks'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:141: in function 'open_quick_fix_list'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:131: in function 'toggle_quick_fix_list'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:68: in function 'toggle_trail_mark_list'
	...k\packer\start\trailblazer.nvim/lua\trailblazer\init.lua:307: in function 'toggle_trail_mark_list'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'setqflist'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:201: in function 'populate_quickfix_list_with_trail_marks'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:141: in function 'open_quick_fix_list'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:131: in function 'toggle_quick_fix_list'
	...r\start\trailblazer.nvim/lua\trailblazer\trails\list.lua:68: in function 'toggle_trail_mark_list'
	...k\packer\start\trailblazer.nvim/lua\trailblazer\init.lua:307: in function 'toggle_trail_mark_list'
	[string ":lua"]:1: in main chunk
```

### Steps To Reproduce

1. Start a blank `Neovim` session.
2. Execute the `TrailBlazerToggleTrailMarkList` command three times.

### Expected Behavior

Should not crash.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 This issue is caused by another plugin. The stack traceback that you posted states, that the plugin `diaglist.nvim` causes this issue in an auto command that it apparently registers. As this plugin alters the default behavior of all quickfix lists it probably tries to update the quickfix list's content in some way that triggers a TrailBlazer callback which in turn changes the qf list again which then causes a recursive loop with `diaglist.nvim` auto command. Maybe there is a setting for `diaglist.nvim` that allows you to disable the behavior if a specific quickfix title is set, so that you can keep using it with normal qf lists but disable it for TrailBlazer qf lists.

**Comment by pidgeon777** [comment]
I confirm that disabling `diaglist.nvim` solve this issue.

**Comment by pidgeon777** [comment]
Still, this issue persists:

https://github.com/LeonHeidelbach/trailblazer.nvim/issues/38
