### ISSUE TITLE
[Bug] Buffers with lowercase and uppercase driver letter cause sorting issue in Windows

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#39]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

Windows 10 21H2

### Describe the bug

Buffers in Neovim running in Windows have a drive letter which can be in uppercase or lowercase.

When adding a mark in a buffer, and if the sort mode is by path, then the mark is added to the mark list in the "wrong" place:

![image](https://user-images.githubusercontent.com/13739892/222398118-e4be72d5-6548-4ba5-9791-8aadee35ff27.png)

This happens when buffers in Neovim have mixed case drive letters in their paths.

A possible fix would be one of the following:

- convert all the drive letters to uppercase, then sort and update the quick-fix list with the transformed drive letters.
- convert all the drive letters to uppercase just during the sorting, then add the drive letters untouched to the quick-fix list.

### Steps To Reproduce

See above.

### Expected Behavior

Buffers should be sorted by path keeping into account the case of the drive letter.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 Should be fixed now f3261b64d76c6e56bfd9d5e0d8d2d3f45270c65b.
