### ISSUE TITLE
bug: Setting a mark on a non-ASCII character causes charater display issues

### ISSUE THREAD

**Issue by miguno** [LeonHeidelbach/trailblazer.nvim#4]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2 (release)

### Operating system/version

macOS 13.1

### Describe the bug

Setting a mark on a non-ASCII character turns the original, marked character into some kind of escape sequence.

### Steps To Reproduce

1. Put the cursor on a non-ASCII character such as `ä` or `⇥`.
2. Set a trail mark.

Marking the non-ASCII characters below changes the displayed characters from their original form:
```
-- non-ASCII character: ä
-- non-ASCII character: ⇥
```

into:

```
-- non-ASCII character: <c3>
-- non-ASCII character: <e2>
```

Removing the marks reverts the displayed characters back into their original form.

### Expected Behavior

The original character should stay intact after setting a mark.

**Comment by LeonHeidelbach** [comment]
Uh that’s an interesting one. It’s an issue with double width chars in lua. I already had to implement a function that correctly returns substrings of strings that contain double width unicode chars, which could be used here. I’ll have a look at it either later today or tomorrow.

**Comment by LeonHeidelbach** [comment]
@miguno This was a tricky one as lua and neovim really don't make it easy for you to work with utf-8 chars directly. However it should be fixed now if you run `:PackerSync`. I really appreciate you taking the time to post about these issues, I don't think I would've found this problem any time soon. Let me know if you find any more :smiley:

**Comment by miguno** [comment]
Yes, the latest code fixes the problem.  Thanks again, @LeonHeidelbach!

**Comment by miguno** [comment]
> I really appreciate you taking the time to post about these issues, I don't think I would've found this problem any time soon. 
But of course. 😃  Thanks for developing this plugin!
