### ISSUE TITLE
[Bug] Drive units of buffer paths are not correctly saved when exporting the `trailblazer` session file in Windows

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#40]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

Windows 10 21H2

### Describe the bug

When saving the trailblazer session, buffer paths are saved in the `.tbsv` file with this format:

```
  "fb_lookup": {
    "C\\Configurations\\Neovim\\config\\LunarVim\\lua\\lvim\\lsp\\init.lua": 109,
    "C\\Work\\Temp\\Neovim\\data\\lunarvim\\site\\pack\\packer\\opt\\vista.vim\\autoload\\vista\\types\\uctags\\c.vim": 115,
    "C\\Work\\Temp\\Neovim\\data\\lunarvim\\site\\pack\\packer\\start\\aerial.nvim\\lua\\aerial\\backends\\lsp\\init.lua": 79,
  },
```

The drive unit should be `C:`. The missing `:` leads to trailblazer not opening the buffers listed in the session file when loading it.

### Steps To Reproduce

See above.

### Expected Behavior

The drive unit should be `C:`.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 Should be fixed now. A classic "off by one" error f61e15996f765c8c1aa17ba1fa6aae87f412d652.
