### ISSUE TITLE
feature: make the readme simpler

### ISSUE THREAD

**Issue by ilan-schemoul** [LeonHeidelbach/trailblazer.nvim#53]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

The package seems very interesting but the GIF and the readme could be more clear.
The readme is very lengthy and leaves me confused even though it's not the first time I try to understand this package

### Describe the solution you'd like

I feel like you could remove the part where you say that the plugin is great, that it will keep getting better and so on. People will download  the package if it solves a problem they have not because the readme says the package is great. You should go straight to what it does with simple examples.
I feel like the better structure is
1. What problem it solves (and doesn't)
2. Basic usage example
3. Advanced features/APIs

### Describe alternatives you've considered

no

**Comment by LeonHeidelbach** [comment]
@ilan-schemoul Thank you for your feedback. Unfortunately, I currently do not have the time to rework the Readme but I would accept PRs if you'd be inclined to take on this task yourself.
