### ISSUE TITLE
feature: show list of marks that have been set

### ISSUE THREAD

**Issue by miguno** [LeonHeidelbach/trailblazer.nvim#7]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Background

Today, the plugin doesn't provide a way to get an overview of the marks that a user has set in an editing session. (It also doesn't persist marks across neovim restarts.)

Neovim's [tag stack](https://neovim.io/doc/user/tagsrch.html) lets you display a list of available tags with `:tags`:

```
   # TO tag      FROM line  in file/text
   1  1 main		 1  harddisk2:text/vim/test
 > 2  2 FuncA		58  i = FuncA(10);
   3  1 FuncC	       357  harddisk2:text/vim/src/amiga.c
```

This is great for remembering where you can navigate/jump to, particularly when marks are spread across different buffers/files; e.g., when you are learning a code base by navigating through the code, or by opening the definition of functions etc. imported from third-party or system libraries.  It would be nice to have a similar list feature in this plugin.

However, I understand that the plugin's main purpose is back-tracking, where marks are quickly placed and then consumed (removed) again. The value of a list feature is likely lower in that context, and more geared towards users that repeatedly use marks to jump back and forth between files and buffers.

### Describe the solution you'd like

A simple list of available marks via a command like `:TrailBlazerListMarks`. The list should include a snippet of information in which the user can deduce in which file/buffer and/or line a mark is set, ideally with a preview of that line.

The list could also or alternatively be integrated with [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) or fzf-related plugins like [fzf.vim](https://github.com/junegunn/fzf.vim), which cover the functionality to display a list and search/pick entries from the list.

This feature is available in some form in neovim's tag stack and in plugins like [harpoon](https://github.com/ThePrimeagen/harpoon).

### Describe alternatives you've considered

See description above, which covers two alternatives.

**Comment by LeonHeidelbach** [comment]
@miguno This is actually a feature that is already on the agenda. I was planning on implementing this through the builtin `quickfixlist` feature first to not have any other dependencies. But having a floating window like harpoon would also be nice, so this will definitely be implemented. The tag stack actually seems pretty interesting, I must say I've never actually used or heard of it before. I think I might have accidentally pressed a key combination once which prompted me that the "tag stack is empty", but did not investigate further.

**Comment by miguno** [comment]
> The tag stack actually seems pretty interesting, I must say I've never actually used or heard of it before. I think I might have accidentally pressed a key combination once which prompted me that the "tag stack is empty", but did not investigate further.

Hah, I have seen that very same "tag stack is empty" message before.  The tag stack is populated AFAIK only via [LSP](https://neovim.io/doc/user/lsp.html), so if you do not have any LSP enabled (and if it is, you also need to "jump around", e.g. via functions like "go to definition") your tag stack should always be empty.

**Comment by LeonHeidelbach** [comment]
Oh, that's interesting. I do use LSPs for every language I work with and also frequently use the "go to definition/refereces ..." etc. functionalities but have not come around the tag stack yet. It just doesn't really seem like a very useful feature if it's only populated by LSP actions though. I saw in the documentation that it's mostly meant for traversing the callstack when debugging. However, you can now do that and much more with TrailBlazer :wink:. Especially after the trail mark list view has been implemented.

**Comment by LeonHeidelbach** [comment]
@miguno The trail mark list feature has been implemented 
6ce89f6. Closing this issue.

**Comment by miguno** [comment]
Thanks!
