### ISSUE TITLE
feature: option to have the plugin work line-wise

### ISSUE THREAD

**Issue by calops** [LeonHeidelbach/trailblazer.nvim#8]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

I dislike having marks displayed as highlights on top of my code.

### Describe the solution you'd like

Having an option to work only line-wise (rather than the current char-wise behavior) would enable the possibility for unobtrusive marks, such as gutter signs or virtual text. Having this could be easily extended in the future once `anticonceal` is implemented in neovim, so we can have the best of both worlds.

### Describe alternatives you've considered

Can't think of any, besides what's already implemented.

**Comment by LeonHeidelbach** [comment]
@calops Yes, I will implement this. Possibly even today if I get to it. Thank you for reminding me!

**Comment by LeonHeidelbach** [comment]
@calops This has now been implemented. You can simply add the following values to your configuration table under the `trail_options` key:

```lua
        trail_mark_in_text_highlights_enabled = false,
        trail_mark_symbol_line_indicators_enabled = true, -- show indicators for all trail marks in symbol column
```

The default config table in the README has also been updated if you want to see where to put the above values exactly. You can also assign a new highlight group to the trail mark indicators under the `hl_groups` key. By default it is set to white:

```lua
        TrailBlazerTrailMark = {
            guifg = "White",
            guibg = "none",
            gui = "bold",
        },
```

Closing this issue. Let me know what you think.
