### ISSUE TITLE
[Feature] Automatically highlight the currently selected mark in the marks list

### ISSUE THREAD

**Issue by pidgeon777** [LeonHeidelbach/trailblazer.nvim#9]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

When navigating between marks, if the marks list is open, the row associated with the currently selected mark is not automatically highlighted.

### Describe the solution you'd like

It would be great if, during marks navigation, the corresponding row in the quick fix panel is automatically highlighted/focused.

### Describe alternatives you've considered

N/A.

**Comment by LeonHeidelbach** [comment]
Sounds good. Will definitely implement this later today.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 The feature has been implemented. Let me know what you think, along with some other improvements. Let me know what you think. Closing this issue.

**Comment by pidgeon777** [comment]
Tested the automatic highlight feature, it works 👍.
